### ISSUE TITLE
Incompatibility to 1.15.1

### ISSUE THREAD

**Issue by SimonIT** [Alvin-LB/NameTagChanger#12]
During initialization via `NameTagChanger.INSTANCE` the following exception is thrown:

```
java.lang.ExceptionInInitializerError: null
	at com.bringholm.nametagchanger.NameTagChanger.enable(NameTagChanger.java:364) ~[?:?]
	at com.bringholm.nametagchanger.NameTagChanger.<init>(NameTagChanger.java:81) ~[?:?]
	at com.bringholm.nametagchanger.NameTagChanger.<clinit>(NameTagChanger.java:60) ~[?:?]
	at de.simonit.changeidentity.ChangeIdentityPlugin.onEnable(ChangeIdentityPlugin.java:52) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[craftbukkit-1.15.1-R0.1-SNAPSHOT.jar:git-Bukkit-2d9db47]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:344) [craftbukkit-1.15.1-R0.1-SNAPSHOT.jar:git-Bukkit-2d9db47]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [craftbukkit-1.15.1-R0.1-SNAPSHOT.jar:git-Bukkit-2d9db47]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:448) [craftbukkit-1.15.1-R0.1-SNAPSHOT.jar:git-Bukkit-2d9db47]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:374) [craftbukkit-1.15.1-R0.1-SNAPSHOT.jar:git-Bukkit-2d9db47]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:447) [craftbukkit-1.15.1-R0.1-SNAPSHOT.jar:git-Bukkit-2d9db47]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:253) [craftbukkit-1.15.1-R0.1-SNAPSHOT.jar:git-Bukkit-2d9db47]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:761) [craftbukkit-1.15.1-R0.1-SNAPSHOT.jar:git-Bukkit-2d9db47]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: com.bringholm.reflectutil.v1_1_1.ReflectUtil$ReflectionException: java.lang.NoSuchMethodException: No method matching , and return type class net.minecraft.server.v1_15_R1.MinecraftServer in class org.bukkit.craftbukkit.v1_15_R1.CraftServer
	at com.bringholm.reflectutil.v1_1_1.ReflectUtil$ReflectionResponse.getOrThrow(ReflectUtil.java:948) ~[?:?]
	at com.bringholm.packetinterceptor.v1_0.PacketInterceptor.<clinit>(PacketInterceptor.java:42) ~[?:?]
	... 13 more
Caused by: java.lang.NoSuchMethodException: No method matching , and return type class net.minecraft.server.v1_15_R1.MinecraftServer in class org.bukkit.craftbukkit.v1_15_R1.CraftServer
	at com.bringholm.reflectutil.v1_1_1.ReflectUtil.getMethodByPredicate(ReflectUtil.java:469) ~[?:?]
	at com.bringholm.reflectutil.v1_1_1.ReflectUtil.getMethodByType(ReflectUtil.java:414) ~[?:?]
	at com.bringholm.packetinterceptor.v1_0.PacketInterceptor.<clinit>(PacketInterceptor.java:42) ~[?:?]
	... 13 more
```
This exception occurs only without using ProtocolLib

**Comment by Alvin-LB** [comment]
As I said in #13, this is because Mojang has changed internals in 1.15. I have to sit down and update this, but I cannot say when I will have the time to do so.
