### ISSUE TITLE
ExceptionInInitializerError

### ISSUE THREAD

**Issue by Level3301** [Alvin-LB/NameTagChanger#17]
Hi i am getting ExceptionInitializerError with this code:
`if (!NameTagChanger.INSTANCE.isEnabled) { //here`
`            NameTagChanger.INSTANCE.enable();`
`}`

```
Caused by: com.bringholm.nametagchanger.ReflectUtil$ReflectionException: java.lang.NoSuchFieldException: modifiers
	at com.bringholm.nametagchanger.ReflectUtil$ReflectionResponse.getOrThrow(ReflectUtil.java:472) ~[?:?]
	at com.bringholm.nametagchanger.ReflectUtil.<clinit>(ReflectUtil.java:34) ~[?:?]
	... 16 more
Caused by: java.lang.NoSuchFieldException: modifiers
	at java.base/java.lang.Class.getDeclaredField(Class.java:2489) ~[?:?]
	at com.bringholm.nametagchanger.ReflectUtil.getDeclaredField(ReflectUtil.java:104) ~[?:?]
	at com.bringholm.nametagchanger.ReflectUtil.<clinit>(ReflectUtil.java:34) ~[?:?]
	... 16 more
```

**Comment by SolusBellator** [comment]
I agree, same problem over here. Been looking for a fix, yet I haven't found anything. @Alvin-LB
