### ISSUE TITLE
I have a probleme :)

### ISSUE THREAD

**Issue by onePlaceholder** [Alvin-LB/NameTagChanger#18]
there is the error:
`java.lang.ExceptionInInitializerError: null
        at com.bringholm.nametagchanger.NameTagChanger.enable(NameTagChanger.java:356) ~[epheria.jar:?]
        at com.bringholm.nametagchanger.NameTagChanger.<init>(NameTagChanger.java:81) ~[epheria.jar:?]
        at com.bringholm.nametagchanger.NameTagChanger.<clinit>(NameTagChanger.java:60) ~[epheria.jar:?]
        at org.theplaceholder.epheria.Epheria.onEnable(Epheria.java:14) ~[epheria.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-350]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-350]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.reload(CraftServer.java:1016) ~[paper-1.18.2.jar:git-Paper-350]
        at org.bukkit.Bukkit.reload(Bukkit.java:909) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.18.2.jar:git-Paper-350]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2306) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2117) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2098) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-350]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1399) ~[paper-1.18.2.jar:git-Paper-350]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-350]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376) ~[paper-1.18.2.jar:git-Paper-350]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-350]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1347) ~[paper-1.18.2.jar:git-Paper-350]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[paper-1.18.2.jar:git-Paper-350]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-350]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.bringholm.reflectutil.v1_1_1.ReflectUtil$ReflectionException: java.lang.NoSuchFieldException: modifiers
        at com.bringholm.reflectutil.v1_1_1.ReflectUtil$ReflectionResponse.getOrThrow(ReflectUtil.java:948) ~[epheria.jar:?]
        at com.bringholm.reflectutil.v1_1_1.ReflectUtil.<clinit>(ReflectUtil.java:59) ~[epheria.jar:?]
        ... 33 more
Caused by: java.lang.NoSuchFieldException: modifiers
        at java.lang.Class.getDeclaredField(Class.java:2610) ~[?:?]
        at com.bringholm.reflectutil.v1_1_1.ReflectUtil.getDeclaredField(ReflectUtil.java:194) ~[epheria.jar:?]
        at com.bringholm.reflectutil.v1_1_1.ReflectUtil.<clinit>(ReflectUtil.java:59) ~[epheria.jar:?]
        ... 33 more
`
here is my code : 'package org.theplaceholder.epheria;

import com.bringholm.nametagchanger.NameTagChanger;
import org.bukkit.plugin.java.JavaPlugin;
import org.theplaceholder.epheria.registers.registerEvents;

public final class Epheria extends JavaPlugin {

    public static Epheria instance;
    @Override
    public void onEnable() {
        instance = this;

        NameTagChanger.INSTANCE.setPlugin(this);
        if (!NameTagChanger.INSTANCE.isEnabled()) {
            NameTagChanger.INSTANCE.enable();
        }

        registerEvents.run();
    }

    @Override
    public void onDisable() {
    }

    public static Epheria getInstance() {return instance;}
}

**Comment by SolusBellator** [comment]
Actually a double of Issue #17, we're looking for the same answer there.
