### ISSUE TITLE
Packet Interceptor error when disabling

### ISSUE THREAD

**Issue by Xesau** [Alvin-LB/NameTagChanger#5]
[21:15:12 WARN]: A task raised an exception. Task: com.bringholm.packetinterceptor.v1_0.PacketInterceptor$$Lambda$59/1466271928@4aef933e
    java.util.NoSuchElementException: packet_interceptor_Kingdoms_0
            at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1119) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]

When reloading, I believe the previous exception causes another exception:

    java.lang.ExceptionInInitializerError: null
            at eu.xesau.kd.Main.onEnable(Main.java:60) ~[?:?]
    Caused by: java.util.NoSuchElementException: packet_handler
            at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1119) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]

**Comment by Alvin-LB** [comment]
Do these exceptions get thrown on the same instance as the ones you describe in #3? If that is the case, these are probably just a consequence of that previous exception.

**Comment by Xesau** [comment]
No. This error occurred after I patched the ConcurrentModificationException.

**Comment by Alvin-LB** [comment]
I don't mean any ConcurrentModificationExceptions, I meant the ClassCastException described in #3.
If that is not the case, please post the full server log of when this occured.

**Comment by Xesau** [comment]
Whoops 😬

Its on the same server, but not sure if they occur at the same time

**Comment by Alvin-LB** [comment]
I have managed to replicate this issue and I am working on a solution. Annoyingly it is very involved with netty internals so I have yet to come up with a solution.

I believe #3 to also be caused by this issue.
